// ============ Base Types ============

export interface ApiError {
  code: string;
  message: string;
  details?: Array<{ field: string; message: string }>;
}

export interface ApiResponse<T> {
  data?: T;
  error?: ApiError;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
    hasMore: boolean;
  };
}

// ============ Auth Types ============

export interface User {
  /** false for OAuth-only accounts (no password set) */
  hasPassword?: boolean;
  id: string;
  email: string;
  name: string;
  avatarUrl: string | null;
  emailVerified?: boolean;
  twoFactorEnabled?: boolean;
  createdAt?: string;
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
}

export interface AuthResponse {
  user: User;
  organization: Organization;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface RegisterInput {
  email: string;
  password: string;
  name: string;
}

// ============ Project Types ============

export interface ProjectServer {
  id: string;
  name: string;
  ipv4: string | null;
  status: string;
  setupStatus: string;
}

export interface Project {
  id: string;
  organizationId: string;
  name: string;
  slug: string;
  description: string | null;
  gitRepoUrl: string | null;
  gitBranch: string | null;
  gitProvider: string | null;
  framework: string | null;
  buildCommand: string | null;
  installCommand: string | null;
  outputDirectory: string | null;
  startCommand: string | null;
  rootDirectory: string | null;
  dockerfilePath: string | null;
  port: number | null;
  autoDeploy: boolean;
  status: ProjectStatus;
  sleepEnabled: boolean;
  sleepAfterMinutes: number;
  /** awake | sleeping | waking */
  sleepState: string;
  lastWakeAt: string | null;
  productionUrl: string | null;
  settings: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  domains?: Domain[];
  serverId: string | null;
  server?: ProjectServer;
  /** Returned once when creating a project; configure Git provider webhook HMAC */
  webhookSecret?: string;
}

/** Matches DB enum `project_status` (deleted projects are excluded from list API). */
export type ProjectStatus = 'active' | 'paused' | 'deleted';

export interface CreateProjectInput {
  name: string;
  description?: string;
  gitRepoUrl?: string;
  gitBranch?: string;
  gitProvider?: 'github' | 'gitlab' | 'bitbucket';
  framework?: string;
  buildCommand?: string;
  installCommand?: string;
  outputDirectory?: string;
  startCommand?: string;
  rootDirectory?: string;
  dockerfilePath?: string;
  port?: number;
  autoDeploy?: boolean;
  serverId?: string;
}

export interface UpdateProjectInput extends Partial<Omit<CreateProjectInput, 'serverId'>> {
  serverId?: string | null;
  sleepEnabled?: boolean;
  sleepAfterMinutes?: number;
}

// ============ Environment Variable Types ============

export type Environment = 'production' | 'staging' | 'development' | 'preview';

export interface EnvVar {
  id: string;
  projectId: string;
  environment: Environment;
  key: string;
  value: string;
  isSecret: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateEnvVarInput {
  key: string;
  value: string;
  environment?: Environment;
  isSecret?: boolean;
}

export interface UpdateEnvVarInput {
  value?: string;
  isSecret?: boolean;
}

// ============ Domain Types ============

export interface Domain {
  id: string;
  projectId: string;
  domain: string;
  isPrimary: boolean;
  isAutoGenerated: boolean;
  verified: boolean;
  sslStatus: string | null;
  verifiedAt: string | null;
  createdAt: string;
}

export interface AddDomainInput {
  domain: string;
  isPrimary?: boolean;
}

export interface DnsSetupInfo {
  domain: string;
  serverIp: string | null;
  recordType: 'A';
  currentIp: string | null;
  isConfigured: boolean;
  message: string;
}

export interface NginxSettings {
  proxyPort?: number;
  proxyTimeout?: number;
  clientMaxBodySize?: string;
  enableWebsocket?: boolean;
  enableGzip?: boolean;
  forceHttps?: boolean;
  customHeaders?: Record<string, string>;
  rateLimit?: {
    enabled: boolean;
    requestsPerSecond: number;
    burst: number;
  };
  caching?: {
    enabled: boolean;
    maxAge: number;
    staleWhileRevalidate?: number;
  };
  customLocationBlocks?: string;
}

// ============ Deployment Types ============

export type DeploymentStatus = 'pending' | 'queued' | 'building' | 'deploying' | 'running' | 'ready' | 'failed' | 'cancelled' | 'stopped';
export type DeploymentTrigger = 'manual' | 'git_push' | 'rollback' | 'redeploy';

export interface Deployment {
  id: string;
  projectId: string;
  status: DeploymentStatus;
  trigger: DeploymentTrigger;
  commitHash: string | null;
  commitMessage: string | null;
  branch: string;
  url: string | null;
  buildLogs: string | null;
  deployLogs: string | null;
  errorMessage: string | null;
  buildStartedAt: string | null;
  buildFinishedAt: string | null;
  deployStartedAt: string | null;
  deployFinishedAt: string | null;
  triggeredBy?: {
    id: string;
    name: string;
    avatarUrl: string | null;
  };
  createdAt: string;
  // For quick rollback support
  dockerImageId?: string | null;
  containerPort?: number | null;
  inQueue?: boolean;
  queueMessage?: string | null;
  queuePosition?: number | null;
}

export interface CreateDeploymentInput {
  commitHash?: string;
  commitMessage?: string;
  branch?: string;
}

// ============ Activity Log Types ============

export type ActivityAction =
  | 'project.created'
  | 'project.updated'
  | 'project.deleted'
  | 'project.paused'
  | 'project.resumed'
  | 'deployment.created'
  | 'deployment.cancelled'
  | 'deployment.redeployed'
  | 'deployment.rolledback'
  | 'deployment.succeeded'
  | 'deployment.failed'
  | 'envvar.created'
  | 'envvar.updated'
  | 'envvar.deleted'
  | 'domain.added'
  | 'domain.removed'
  | 'domain.verified'
  | 'domain.set_primary'
  | 'apikey.created'
  | 'apikey.revoked'
  | 'member.invited'
  | 'member.removed'
  | 'member.role_changed'
  | 'settings.updated'
  | 'webhook.regenerated'
  | 'notification.channel_created'
  | 'notification.channel_updated'
  | 'notification.channel_deleted'
  | 'healthcheck.enabled'
  | 'healthcheck.disabled'
  | 'healthcheck.updated';

export interface ActivityLogUser {
  id: string;
  name: string | null;
  email: string;
  avatarUrl: string | null;
}

export interface ActivityLogProject {
  id: string;
  name: string;
  slug: string;
}

export interface ActivityLog {
  id: string;
  action: ActivityAction;
  description: string;
  metadata: Record<string, unknown>;
  createdAt: string;
  user: ActivityLogUser | null;
  project: ActivityLogProject | null;
}

export interface ActivityLogFilters {
  projectId?: string;
  userId?: string;
  actions?: ActivityAction[];
  limit?: number;
  offset?: number;
}

// ============ Health Check Types ============

export type HealthCheckStatus = 'healthy' | 'unhealthy' | 'timeout' | 'unknown';

export interface HealthCheckConfig {
  id: string;
  projectId: string;
  endpoint: string;
  intervalSeconds: number;
  timeoutSeconds: number;
  unhealthyThreshold: number;
  autoRestart: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface HealthCheckConfigInput {
  endpoint?: string;
  intervalSeconds?: number;
  timeoutSeconds?: number;
  unhealthyThreshold?: number;
  autoRestart?: boolean;
  isActive?: boolean;
}

export interface HealthCheckLog {
  id: string;
  projectId: string;
  deploymentId: string | null;
  status: HealthCheckStatus;
  responseTimeMs: number | null;
  statusCode: number | null;
  consecutiveFailures: number;
  actionTaken: string | null;
  errorMessage: string | null;
  checkedAt: string;
}

// ============ Database Types ============

export type DatabaseType = 'postgresql' | 'mysql' | 'redis' | 'mongodb';
export type DatabaseStatus = 'provisioning' | 'running' | 'stopped' | 'error' | 'deleting';

export interface Database {
  id: string;
  organizationId: string;
  serverId: string | null;
  name: string;
  description: string | null;
  type: DatabaseType;
  version: string;
  host: string | null;
  port: number;
  databaseName: string;
  username: string;
  password: string; // Will be masked
  connectionString: string | null; // Will be masked
  status: DatabaseStatus;
  statusMessage: string | null;
  maxConnections: number | null;
  storageMb: number | null;
  usedStorageMb: number | null;
  backupEnabled: boolean;
  backupRetentionDays: number | null;
  lastBackupAt: string | null;
  containerName: string | null;
  containerPort: number | null;
  externalAccess: boolean;
  createdAt: string;
  updatedAt: string;
  server?: {
    id: string;
    name: string;
    ipv4: string | null;
    status: string;
  };
}

export interface DatabaseCredentials {
  host: string | null;
  port: number;
  databaseName: string;
  username: string;
  password: string;
  connectionString: string | null;
}

export interface CreateDatabaseInput {
  name: string;
  description?: string;
  type: DatabaseType;
  version?: string;
  serverId: string;
}

export interface UpdateDatabaseInput {
  name?: string;
  description?: string;
  backupEnabled?: boolean;
  backupRetentionDays?: number;
}

export interface DatabaseConnection {
  id: string;
  databaseId: string;
  projectId: string;
  envVarName: string;
  permissions: 'readonly' | 'readwrite';
  createdAt: string;
  project?: {
    id: string;
    name: string;
    slug: string;
  };
  database?: Database;
}

export interface ConnectDatabaseInput {
  projectId: string;
  envVarName?: string;
  permissions?: 'readonly' | 'readwrite';
}

export interface DatabaseTypeInfo {
  type: DatabaseType;
  defaultVersion: string;
  defaultPort: number;
}

// ============ Database Backup Types ============

export type BackupType = 'automatic' | 'manual';
export type BackupStatus = 'creating' | 'completed' | 'failed' | 'restoring' | 'restored' | 'deleted';

export interface DatabaseBackup {
  id: string;
  databaseId: string;
  name: string;
  type: BackupType;
  status: BackupStatus;
  sizeMb: number | null;
  filePath: string | null;
  metadata: Record<string, unknown>;
  errorMessage: string | null;
  startedAt: string;
  completedAt: string | null;
  expiresAt: string | null;
}

// ============ Database Studio (data browser) Types ============

export type StudioEngine = 'postgresql' | 'mysql';

export interface StudioTable {
  schema: string;
  name: string;
  kind: 'table' | 'view';
  rowEstimate: number;
  sizeBytes: number | null;
  hasPrimaryKey: boolean;
}

export interface StudioTypeInfo {
  name: string;
  hasLength?: boolean;
  hasScale?: boolean;
  autoIncrementable?: boolean;
}

export interface StudioTableList {
  engine: StudioEngine;
  defaultSchema: string;
  tables: StudioTable[];
  columnTypes: StudioTypeInfo[];
  /** what the signed-in user may do here; write actions are hidden when this is 'read' */
  access: 'read' | 'write';
}

export interface StudioColumn {
  name: string;
  dataType: string;
  isNullable: boolean;
  defaultValue: string | null;
  isPrimaryKey: boolean;
  editable: boolean;
  ordinal: number;
}

export type StudioFilterOperator =
  | 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte'
  | 'contains' | 'startsWith' | 'endsWith' | 'isNull' | 'isNotNull';

export interface StudioFilter {
  column: string;
  operator: StudioFilterOperator;
  value?: string;
}

export interface StudioRows {
  schema: string;
  name: string;
  kind: 'table' | 'view';
  columns: StudioColumn[];
  primaryKey: string[];
  editable: boolean;
  rows: Record<string, unknown>[];
  page: number;
  pageSize: number;
  total: number;
  totalCapped: boolean;
  /** true when `total` is the planner's estimate rather than a counted value */
  totalEstimated: boolean;
}

export interface StudioRowsQuery {
  schema?: string;
  table: string;
  page?: number;
  pageSize?: number;
  orderBy?: string;
  orderDir?: 'asc' | 'desc';
  filters?: StudioFilter[];
}

export interface StudioMutationResult {
  affected: number;
}

export interface StudioInsertInput {
  schema?: string;
  table: string;
  values: Record<string, unknown>;
}

export interface StudioUpdateInput extends StudioInsertInput {
  pk: Record<string, unknown>;
}

export interface StudioDeleteInput {
  schema?: string;
  table: string;
  pks: Record<string, unknown>[];
}

export interface StudioQueryResult {
  columns: string[];
  rows: Record<string, unknown>[];
  rowCount: number;
  truncated: boolean;
  message: string | null;
  durationMs: number;
  readOnly: boolean;
  command: string | null;
  affected: number | null;
}

export interface StudioSchemaTable {
  schema: string;
  name: string;
  kind: 'table' | 'view';
  columns: { name: string; dataType: string }[];
}

export interface StudioSchemaMap {
  engine: StudioEngine;
  defaultSchema: string;
  tables: StudioSchemaTable[];
  truncated: boolean;
}

// ============ Database Studio schema (DDL) Types ============

export interface StudioColumnDefinition {
  name: string;
  type: string;
  length?: number | null;
  scale?: number | null;
  nullable?: boolean;
  primaryKey?: boolean;
  autoIncrement?: boolean;
  unique?: boolean;
  defaultValue?: string | null;
}

export interface StudioCreateTableInput {
  schema?: string;
  name: string;
  columns: StudioColumnDefinition[];
}

export interface StudioTableTarget {
  schema?: string;
  table: string;
}

export interface StudioRenameTableInput extends StudioTableTarget {
  newName: string;
}

export interface StudioAddColumnInput extends StudioTableTarget {
  column: StudioColumnDefinition;
}

export interface StudioDropColumnInput extends StudioTableTarget {
  column: string;
}

// ============ Database Studio indexes & performance ============

export interface StudioIndex {
  name: string;
  columns: string[];
  isUnique: boolean;
  isPrimary: boolean;
  method: string | null;
  definition: string | null;
  sizeBytes: number | null;
}

export interface StudioCreateIndexInput {
  schema?: string;
  table: string;
  name?: string;
  columns: string[];
  unique?: boolean;
  method?: string;
}

export interface StudioDropIndexInput {
  schema?: string;
  table: string;
  name: string;
}

export interface StudioSlowQuery {
  id: string;
  query: string;
  calls: number;
  totalMs: number;
  meanMs: number;
  rows: number;
}

export interface StudioRunningQuery {
  id: string;
  user: string | null;
  state: string | null;
  runningMs: number | null;
  query: string | null;
}

export interface StudioPerformance {
  engine: StudioEngine;
  slowQueries: { available: boolean; hint: string | null; items: StudioSlowQuery[] };
  running: { available: boolean; hint: string | null; items: StudioRunningQuery[] };
}

// ============ Database Studio: MongoDB & Redis ============

export interface MongoCollection {
  name: string;
  type: string;
  count: number;
}

export interface MongoDocumentsPage {
  documents: Record<string, unknown>[];
  total: number;
  totalCapped: boolean;
  page: number;
  pageSize: number;
}

export interface MongoDocumentsQuery {
  collection: string;
  filter?: string;
  sort?: string;
  page?: number;
  pageSize?: number;
}

export type RedisKeyType = 'string' | 'list' | 'set' | 'zset' | 'hash' | 'stream' | 'none';

export interface RedisKeySummary {
  name: string;
  type: RedisKeyType;
  ttl: number;
}

export interface RedisScanPage {
  cursor: string;
  keys: RedisKeySummary[];
  keyCount: number;
}

export interface RedisKeyValue {
  name: string;
  type: RedisKeyType;
  ttl: number;
  size: number;
  truncated: boolean;
  value?: string;
  items?: string[];
  entries?: { field: string; value: string }[];
}

export interface StudioImportInput {
  schema?: string;
  table: string;
  columns: string[];
  rows: (string | null)[][];
  emptyAsNull?: boolean;
}
