'use client';

import { useState } from 'react';
import { Check, Copy, ExternalLink, Globe } from 'lucide-react';
import { useDomains, useTranslation } from '@/hooks';
import { DomainCard } from './DomainCard';
import { NginxSettingsModal } from './NginxSettingsModal';

export function DomainsTab({
  projectId,
  domains,
  onAdd,
  onDelete,
  onSetPrimary,
  onVerify,
  isVerifying,
  t,
}: {
  projectId: string;
  domains: ReturnType<typeof useDomains>['data'];
  onAdd: (domain: string) => void;
  onDelete: (id: string) => void;
  onSetPrimary: (id: string) => void;
  onVerify: (id: string) => void;
  isVerifying: boolean;
  t: ReturnType<typeof useTranslation>['t'];
}) {
  const { locale } = useTranslation();
  const [showAddForm, setShowAddForm] = useState(false);
  const [newDomain, setNewDomain] = useState('');
  const [expandedDomain, setExpandedDomain] = useState<string | null>(null);
  const [copiedIp, setCopiedIp] = useState(false);
  const [copiedAutoUrl, setCopiedAutoUrl] = useState(false);
  const [settingsDomainId, setSettingsDomainId] = useState<string | null>(null);

  const autoSubdomain = domains?.find((d) => d.isAutoGenerated);
  const customDomains = domains?.filter((d) => !d.isAutoGenerated) || [];

  const handleAdd = () => {
    if (!newDomain) return;
    onAdd(newDomain);
    setNewDomain('');
    setShowAddForm(false);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedIp(true);
    setTimeout(() => setCopiedIp(false), 2000);
  };

  const copyAutoUrl = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedAutoUrl(true);
    setTimeout(() => setCopiedAutoUrl(false), 2000);
  };

  const getSslStatusBadge = (sslStatus: string | null) => {
    switch (sslStatus) {
      case 'active':
        return { class: 'badge-success', text: t('projectDetail', 'sslActive') };
      case 'configuring':
        return { class: 'badge-warning', text: locale === 'tr' ? 'SSL yapılandırılıyor' : 'SSL configuring' };
      case 'failed':
        return { class: 'badge-error', text: locale === 'tr' ? 'SSL başarısız' : 'SSL failed' };
      default:
        return { class: 'badge-neutral', text: locale === 'tr' ? 'SSL bekliyor' : 'SSL pending' };
    }
  };

  return (
    <div className="space-y-4 min-w-0">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-sm text-[var(--text-secondary)] min-w-0">
          {t('projectDetail', 'domainsDesc')}
        </p>
        <button onClick={() => setShowAddForm(true)} className="btn btn-primary justify-center w-full sm:w-auto shrink-0">
          <Globe className="w-4 h-4" />
          {t('projectDetail', 'addDomain')}
        </button>
      </div>

      {showAddForm && (
        <form
          className="dash-card p-4 flex flex-col gap-3 sm:flex-row sm:items-end"
          onSubmit={(e) => {
            e.preventDefault();
            handleAdd();
          }}
        >
          <label className="flex-1 min-w-0">
            <span className="dash-section-label block mb-2">{t('projectDetail', 'domain')}</span>
            <input
              type="text"
              value={newDomain}
              onChange={(e) => setNewDomain(e.target.value)}
              placeholder="example.com"
              className="input terminal-text"
              autoFocus
            />
          </label>
          <div className="flex items-center justify-end gap-2 shrink-0">
            <button type="button" onClick={() => setShowAddForm(false)} className="btn btn-ghost">{t('common', 'cancel')}</button>
            <button type="submit" className="btn btn-primary">{t('projectDetail', 'addDomain')}</button>
          </div>
        </form>
      )}

      <div className="dash-rows">
        {/* Auto-generated Pushify URL */}
        {autoSubdomain && (
          <div className="dash-row flex items-center justify-between gap-3">
            <div className="flex items-center gap-3 min-w-0 flex-1">
              <span className="dash-status-dot is-success" aria-hidden />
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-x-2.5 gap-y-1">
                  <a
                    href={`https://${autoSubdomain.domain}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="terminal-text text-[13px] text-[var(--text-primary)] hover:underline underline-offset-2 inline-flex items-center gap-1 min-w-0"
                  >
                    <span className="truncate">{autoSubdomain.domain}</span>
                    <ExternalLink className="w-3 h-3 shrink-0 text-[var(--text-muted)]" />
                  </a>
                  <span className="dash-section-label">{t('projectDetail', 'pushifyUrl')}</span>
                  <span className="badge badge-success">{t('projectDetail', 'sslActive')}</span>
                </div>
              </div>
            </div>
            <button
              type="button"
              onClick={() => copyAutoUrl(`https://${autoSubdomain.domain}`)}
              aria-label={t('projectDetail', 'copyUrl')}
              title={t('projectDetail', 'copyUrl')}
              className="w-8 h-8 rounded-full flex items-center justify-center text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--hover-overlay-md)] transition-colors shrink-0"
            >
              {copiedAutoUrl ? (
                <Check className="w-4 h-4 text-[var(--status-success)]" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
            </button>
          </div>
        )}

        {customDomains.map((domain) => (
          <DomainCard
            key={domain.id}
            projectId={projectId}
            domain={domain}
            isExpanded={expandedDomain === domain.id}
            onToggleExpand={() => setExpandedDomain(expandedDomain === domain.id ? null : domain.id)}
            onVerify={onVerify}
            onSetPrimary={onSetPrimary}
            onDelete={onDelete}
            onOpenSettings={() => setSettingsDomainId(domain.id)}
            isVerifying={isVerifying}
            copiedIp={copiedIp}
            onCopyIp={copyToClipboard}
            getSslStatusBadge={getSslStatusBadge}
            t={t}
          />
        ))}

        {customDomains.length === 0 && (
          <div className="dash-row py-8 text-center">
            <p className="text-sm text-[var(--text-primary)]">{t('projectDetail', 'noCustomDomains')}</p>
            <p className="text-[13px] text-[var(--text-muted)] mt-1">{t('projectDetail', 'noCustomDomainsDesc')}</p>
          </div>
        )}
      </div>

      {/* Nginx Settings Modal */}
      {settingsDomainId && (
        <NginxSettingsModal
          projectId={projectId}
          domainId={settingsDomainId}
          domainName={domains?.find(d => d.id === settingsDomainId)?.domain || ''}
          onClose={() => setSettingsDomainId(null)}
          t={t}
        />
      )}
    </div>
  );
}
