'use client';

import { useState } from 'react';
import { Check, Copy, ExternalLink, Globe } from 'lucide-react';
import { useDomains, useTranslation } from '@/hooks';
import { DomainCard } from './DomainCard';
import { NginxSettingsModal } from './NginxSettingsModal';

export function DomainsTab({
  projectId,
  domains,
  onAdd,
  onDelete,
  onSetPrimary,
  onVerify,
  isVerifying,
  t,
}: {
  projectId: string;
  domains: ReturnType<typeof useDomains>['data'];
  onAdd: (domain: string) => void;
  onDelete: (id: string) => void;
  onSetPrimary: (id: string) => void;
  onVerify: (id: string) => void;
  isVerifying: boolean;
  t: ReturnType<typeof useTranslation>['t'];
}) {
  const [showAddForm, setShowAddForm] = useState(false);
  const [newDomain, setNewDomain] = useState('');
  const [expandedDomain, setExpandedDomain] = useState<string | null>(null);
  const [copiedIp, setCopiedIp] = useState(false);
  const [copiedAutoUrl, setCopiedAutoUrl] = useState(false);
  const [settingsDomainId, setSettingsDomainId] = useState<string | null>(null);

  const autoSubdomain = domains?.find((d) => d.isAutoGenerated);
  const customDomains = domains?.filter((d) => !d.isAutoGenerated) || [];

  const handleAdd = () => {
    if (!newDomain) return;
    onAdd(newDomain);
    setNewDomain('');
    setShowAddForm(false);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedIp(true);
    setTimeout(() => setCopiedIp(false), 2000);
  };

  const copyAutoUrl = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedAutoUrl(true);
    setTimeout(() => setCopiedAutoUrl(false), 2000);
  };

  const getSslStatusBadge = (sslStatus: string | null) => {
    switch (sslStatus) {
      case 'active':
        return { class: 'badge-success', text: 'SSL Active' };
      case 'configuring':
        return { class: 'badge-warning', text: 'SSL Configuring' };
      case 'failed':
        return { class: 'badge-error', text: 'SSL Failed' };
      default:
        return { class: 'badge-neutral', text: 'SSL Pending' };
    }
  };

  return (
    <div className="space-y-4 min-w-0">
      {/* Auto-generated Pushify URL */}
      {autoSubdomain && (
        <div className="p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--accent-cyan)]/30 border-l-4 border-l-[var(--accent-cyan)] min-w-0">
          <div className="flex items-start justify-between gap-3">
            <div className="flex items-start gap-3 min-w-0 flex-1">
              <Globe className="w-5 h-5 text-[var(--accent-cyan)] shrink-0 mt-0.5" />
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-xs font-medium text-[var(--accent-cyan)] uppercase tracking-wider">Pushify URL</span>
                  <span className="badge badge-success text-xs">SSL Active</span>
                </div>
                <a
                  href={`https://${autoSubdomain.domain}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="terminal-text font-medium text-[var(--text-primary)] hover:text-[var(--accent-cyan)] transition-colors flex items-center gap-1 mt-0.5 break-all"
                >
                  <span className="truncate">{autoSubdomain.domain}</span>
                  <ExternalLink className="w-3.5 h-3.5 shrink-0" />
                </a>
              </div>
            </div>
            <button
              onClick={() => copyAutoUrl(`https://${autoSubdomain.domain}`)}
              className="w-9 h-9 rounded-lg flex items-center justify-center text-[var(--text-muted)] hover:text-[var(--text-secondary)] hover:bg-[var(--bg-tertiary)] transition-colors"
            >
              {copiedAutoUrl ? (
                <Check className="w-4 h-4 text-[var(--status-success)]" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
            </button>
          </div>
        </div>
      )}

      {/* Custom Domains Section */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-sm text-[var(--text-secondary)] min-w-0">
          {t('projectDetail', 'domainsDesc')}
        </p>
        <button onClick={() => setShowAddForm(true)} className="btn btn-primary justify-center w-full sm:w-auto shrink-0">
          <Globe className="w-4 h-4" />
          {t('projectDetail', 'addDomain')}
        </button>
      </div>

      {showAddForm && (
        <div className="p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-subtle)] space-y-4">
          <div>
            <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">{t('projectDetail', 'domain')}</label>
            <input
              type="text"
              value={newDomain}
              onChange={(e) => setNewDomain(e.target.value)}
              placeholder="example.com"
              className="input terminal-text"
            />
          </div>
          <div className="flex items-center justify-end gap-2">
            <button onClick={() => setShowAddForm(false)} className="btn btn-ghost">{t('common', 'cancel')}</button>
            <button onClick={handleAdd} className="btn btn-primary">{t('projectDetail', 'addDomain')}</button>
          </div>
        </div>
      )}

      {customDomains.length === 0 && !showAddForm ? (
        <div className="p-12 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-subtle)] text-center">
          <Globe className="w-12 h-12 text-[var(--text-muted)] mx-auto mb-3" />
          <h3 className="text-lg font-medium mb-2">{t('projectDetail', 'noCustomDomains')}</h3>
          <p className="text-[var(--text-secondary)]">{t('projectDetail', 'noCustomDomainsDesc')}</p>
        </div>
      ) : customDomains.length > 0 && (
        <div className="space-y-3">
          {customDomains.map((domain) => (
            <DomainCard
              key={domain.id}
              projectId={projectId}
              domain={domain}
              isExpanded={expandedDomain === domain.id}
              onToggleExpand={() => setExpandedDomain(expandedDomain === domain.id ? null : domain.id)}
              onVerify={onVerify}
              onSetPrimary={onSetPrimary}
              onDelete={onDelete}
              onOpenSettings={() => setSettingsDomainId(domain.id)}
              isVerifying={isVerifying}
              copiedIp={copiedIp}
              onCopyIp={copyToClipboard}
              getSslStatusBadge={getSslStatusBadge}
              t={t}
            />
          ))}

          {/* Nginx Settings Modal */}
          {settingsDomainId && (
            <NginxSettingsModal
              projectId={projectId}
              domainId={settingsDomainId}
              domainName={domains?.find(d => d.id === settingsDomainId)?.domain || ''}
              onClose={() => setSettingsDomainId(null)}
              t={t}
            />
          )}
        </div>
      )}
    </div>
  );
}
