#!/usr/bin/env bash
# Deploy the dashboard without taking it down — Jenkins "Execute shell":
#
#   sudo -E bash "${WORKSPACE}/scripts/jenkins-deploy.sh"
#
# The old job deleted node_modules and .next in the directory the live site ran from, so the site
# answered "Internal Server Error" for the whole install + build. Now:
#   1. build here, in the Jenkins workspace — the live site runs from $ROOT/current and is untouched
#   2. copy the standalone build into $ROOT/releases/<time> and try it on a spare port
#   3. point $ROOT/current at it (one atomic rename) and let pm2 restart the two cluster
#      instances one after the other — one of them always answers
# The last $KEEP releases stay on disk; to roll back, point `current` at an older one and
# `pm2 reload <app>`.
#
# The first run takes over the pm2 app from ecosystem.config.js (same name and port, its env
# kept); that switch from the old process to the new one is the only moment without an answer.
set -euo pipefail

WORKSPACE_DIR="${WORKSPACE:-$(cd "$(dirname "$0")/.." && pwd)}"
ROOT="${PUSHIFY_FRONTEND_ROOT:-/var/www/pushify-frontend}"
KEEP="${PUSHIFY_FRONTEND_KEEP:-3}"
INSTANCES="${PUSHIFY_FRONTEND_INSTANCES:-2}"
TEST_PORT="${PUSHIFY_FRONTEND_TEST_PORT:-3999}"

cd "$WORKSPACE_DIR"
log() { echo "==> $*"; }

# App name, port and env of the running dashboard: from ecosystem.config.js when there is one.
read_app() {
  node -e '
    let app = {};
    try { app = (require(process.argv[1]).apps || [])[0] || {}; } catch {}
    const env = Object.assign({}, app.env || {}, app.env_production || {});
    process.stdout.write(JSON.stringify({ name: app.name || "pushify-frontend", port: String(env.PORT || 3000), env }));
  ' "$WORKSPACE_DIR/ecosystem.config.js"
}
APP_JSON="$(read_app)"
APP_NAME="${PUSHIFY_FRONTEND_APP:-$(node -e 'console.log(JSON.parse(process.argv[1]).name)' "$APP_JSON")}"
PORT="${PUSHIFY_FRONTEND_PORT:-$(node -e 'console.log(JSON.parse(process.argv[1]).port)' "$APP_JSON")}"
log "Dashboard: pm2 app '$APP_NAME' on port $PORT, releases in $ROOT"

# 1. Build (NEXT_PUBLIC_* come from the .env files here and are baked in now)
if [[ -f package-lock.json ]]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
rm -rf .next
npm run build
[[ -f .next/standalone/server.js ]] || { echo "ERROR: no .next/standalone/server.js — is output: 'standalone' set?" >&2; exit 1; }

# 2. Assemble the release: standalone server + static assets + public + runtime .env files
RELEASE="$ROOT/releases/$(date -u +%Y%m%d%H%M%S)"
mkdir -p "$RELEASE/.next"
cp -a .next/standalone/. "$RELEASE/"
cp -a .next/static "$RELEASE/.next/static"
cp -a public "$RELEASE/public"
for f in .env .env.production .env.local .env.production.local; do
  [[ -f "$f" ]] && cp -a "$f" "$RELEASE/"
done
log "Release assembled: $RELEASE"

# …and try it before anyone else does
( cd "$RELEASE" && PORT="$TEST_PORT" HOSTNAME=127.0.0.1 NODE_ENV=production node server.js >"$RELEASE/.smoke.log" 2>&1 ) &
SMOKE_PID=$!
ok=""
for _ in $(seq 1 30); do
  code="$(curl -s -o /dev/null -m 5 -w '%{http_code}' "http://127.0.0.1:$TEST_PORT/" || true)"
  if [[ "$code" =~ ^[23] ]]; then ok=1; break; fi
  sleep 1
done
kill "$SMOKE_PID" 2>/dev/null || true
wait "$SMOKE_PID" 2>/dev/null || true
if [[ -z "$ok" ]]; then
  echo "ERROR: the new release did not answer on port $TEST_PORT — the live site was not touched" >&2
  tail -30 "$RELEASE/.smoke.log" >&2 || true
  rm -rf "$RELEASE"
  exit 1
fi
log "Release answers on :$TEST_PORT"

# 3. Switch: `current` now points at the new release (rename is atomic)
ln -sfn "$RELEASE" "$ROOT/current.next"
mv -Tf "$ROOT/current.next" "$ROOT/current"

cat >"$ROOT/ecosystem.config.cjs" <<EOF
// Generated by scripts/jenkins-deploy.sh — edit the script, not this file.
module.exports = {
  apps: [{
    name: ${APP_NAME@Q},
    script: '$ROOT/current/server.js',
    cwd: '$ROOT/current',
    exec_mode: 'cluster',
    instances: $INSTANCES,
    autorestart: true,
    max_memory_restart: '1G',
    env: Object.assign($(node -e 'console.log(JSON.stringify(JSON.parse(process.argv[1]).env))' "$APP_JSON"), {
      NODE_ENV: 'production',
      PORT: '$PORT',
      // The standalone server binds to \$HOSTNAME, which shells set to the machine's name — pin it
      // (all interfaces, like \`next start\`).
      HOSTNAME: '${PUSHIFY_FRONTEND_HOST:-0.0.0.0}',
    }),
  }],
};
EOF

current_exec="$(pm2 jlist 2>/dev/null | node -e '
  let d = ""; process.stdin.on("data", (c) => (d += c)).on("end", () => {
    const p = (JSON.parse(d || "[]")).find((x) => x.name === process.argv[1]);
    process.stdout.write(p ? `${p.pm2_env.exec_mode}|${p.pm2_env.pm_exec_path}` : "");
  });' "$APP_NAME")"

if [[ "$current_exec" == "cluster_mode|$ROOT/current/server.js" ]]; then
  log "Rolling restart of '$APP_NAME'"
  pm2 reload "$ROOT/ecosystem.config.cjs" --update-env
else
  # First run (or a different setup): replace the old process — the one short gap
  log "Taking over '$APP_NAME' (was: ${current_exec:-not running})"
  pm2 delete "$APP_NAME" >/dev/null 2>&1 || true
  pm2 start "$ROOT/ecosystem.config.cjs"
fi
pm2 save

# 4. Keep the last $KEEP releases (never the live one)
live="$(readlink -f "$ROOT/current")"
ls -1dt "$ROOT"/releases/* 2>/dev/null | tail -n +$((KEEP + 1)) | while read -r old; do
  [[ "$(readlink -f "$old")" == "$live" ]] || rm -rf "$old"
done

for _ in $(seq 1 20); do
  code="$(curl -s -o /dev/null -m 5 -w '%{http_code}' "http://127.0.0.1:$PORT/" || true)"
  [[ "$code" =~ ^[23] ]] && { log "Live on :$PORT (HTTP $code) — $(basename "$RELEASE")"; exit 0; }
  sleep 1
done
echo "WARN: :$PORT is not answering yet — check: pm2 logs $APP_NAME" >&2
